### ISSUE TITLE
DMason on Windows can't create worker directories

### ISSUE THREAD

**Issue by Robadob** [isislab-unisa/dmason#1]
I've just built DMason on Windows 7 (JDK 1.8.0_73), when I executed a worker (after setting the master running) I received the below error.

```
Directory not created : C:\dmason\dmason\worker\WORKER-143.167.101.134-32a85b2c:1544cd4d92f:-8000\25-04-16-10_51\simulations
Directory not created : C:\dmason\dmason\worker\WORKER-143.167.101.134-32a85b2c:1544cd4d92f:-8000\25-04-16-10_51\err
java.io.FileNotFoundException: C:\dmason\dmason\worker\WORKER-143.167.101.134-32a85b2c:1544cd4d92f:-8000\25-04-16-10_51\err\workerWORKER-143.167.101.134-2a85b2c:1544cd4d92f:-8000.err (The filename, directory name, or volume label syntax is incorrect)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at it.isislab.dmason.experimentals.systemmanagement.worker.Worker.generateFolders(Worker.java:944)
        at it.isislab.dmason.experimentals.systemmanagement.worker.Worker.connectToMessageBroker(Worker.java:140)
        at it.isislab.dmason.experimentals.systemmanagement.worker.Worker.<init>(Worker.java:127)
        at it.isislab.dmason.experimentals.systemmanagement.Manager.startWorker(Manager.java:283)
        at it.isislab.dmason.experimentals.systemmanagement.Manager.doMain(Manager.java:253)
        at it.isislab.dmason.experimentals.systemmanagement.Manager.main(Manager.java:77)
```

This is caused by the file path containing the character `:`, looking through the code it appears the call `new UID()` at `it.isislab.dmason.experimentals.systemmanagement.worker.Worker.java:139` is to blame.

Replacing `new UID()` with `(new UID()).toString().replace(":","_")` should replace the offending characters.

Presumably UIDs on Linux are of a different format.

**Comment by miccar** [comment]
You have explained the problem. We delete our line of code **.replace(":","")** by mistake.  We will test dmason system management  on Windows in this week. Thanks for your interest

**Comment by Robadob** [comment]
https://github.com/isislab-unisa/dmason/commit/3459f048a1e3024f8bf3704305fc2dfef89b3feb
